name: sudest_market
services:
  postgres:
    container_name: sudest_market_postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=sudest_market'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=root'

    volumes:
      - sudest_data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'

volumes:
  sudest_data: