server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sudest_market?autoReconnect=true
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        default_schema: public
    open-in-view: false

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          private-key: classpath:app.private.key
          public-key: classpath:app.public.key

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    properties:
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
    host: smtp.gmail.com
    port: 587
    username: aaittamghart8@gmail.com
    password: fuzjjtklcvrbxpvj


app:
  frontend:
    domain: http://localhost:4200